name = "p2p-tracker-api"
main = "src/index.js"
compatibility_date = "2026-03-10"

# [triggers]
# crons = ["*/5 * * * *"]

[[kv_namespaces]]
binding = "P2P_KV"
id = "00e9cb0899964d34a89b8b41376682ed"

[[d1_databases]]
binding = "DB"
database_name = "crypto-tracker"
database_id = "e51dd932-5912-4a1b-b354-ff03bc25d23e"
migrations_dir = "migrations"

[vars]
ALLOWED_ORIGINS = "https://p2p-tracker.taheito26.workers.dev,https://p2p-tracker.pages.dev,https://tracker.pages.dev,https://lovable.dev"
AUTH_SOURCE = "cloudflare-access"
